name: 报告Bug / Bug Report
description: 提交一个bug / Submit a bug report
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## 问题描述 / Problem Description
        <!-- 请使用中英文双语描述，中文在前 / Please describe in bilingual, Chinese first -->

  - type: textarea
    id: description-zh
    attributes:
      label: 中文描述
      description: 请用中文描述问题
      placeholder: 清晰地描述遇到的bug...
    validations:
      required: true

  - type: textarea
    id: description-en
    attributes:
      label: English Description
      description: Please describe the issue in English
      placeholder: Clearly describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤 / Steps to Reproduce
      description: 如何复现这个问题 / How to reproduce this issue
      placeholder: |
        1. 执行... / Run...
        2. 输入... / Input...
        3. 出现错误 / Error occurs
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: 期望结果 / Expected Behavior
      description: 你期望发生什么 / What did you expect to happen

  - type: textarea
    id: actual
    attributes:
      label: 实际结果 / Actual Behavior
      description: 实际发生了什么 / What actually happened

  - type: input
    id: environment
    attributes:
      label: 环境信息 / Environment
      description: 操作系统、Kimi版本等 / OS, Kimi version, etc.
      placeholder: Windows 11, Kimi CLI v2.0
